const page = document.body.dataset.page;
document.querySelectorAll('[href="gpt/index.html"]').forEach(link => { link.href = 'index.html'; });
const data = {
  magazine:{title:'The <em>Magazine.</em>', kicker:'The independent journal', intro:'An attentive record of contemporary practice.', copy:'A biannual digital publication for the ways artists make, think, and keep going. Each volume moves between studio visits, material research, legal clarity, and unhurried criticism.', items:[['01','Current issue — Material Intelligence','28 artists on tactility, intuition, clay, pigment and the slow intelligence of making.'],['02','Studio Visits & Process','Inside working spaces, from first sketch to final surface.'],['03','Material & Technique','Pigments, armatures, stone, metalwork and the methods that make work last.'],['04','The Artist’s Mind','Conversations about ambition, loneliness, resilience and creative blocks.']]},
  awards:{title:'The Art <em>Awards.</em>', kicker:'AURELIA 2026', intro:'A generous stage for work with something at stake.', copy:'The AURELIA Art Awards are an annual international programme for contemporary painting, sculpture and mixed media. Blind review, specialist juries, and artists retain complete ownership of their work.', items:[['01','Painting & 2D Media','Oil, acrylic, watercolour, drawing, figurative, abstract and mixed media.'],['02','Sculpture & 3D Media','Stone, wood, metal, bronze, ceramic, assemblage and spatial installation.'],['03','Art Publications','Artist monographs, independent zines and exhibition catalogues.'],['04','Jury & calendar','Early entry: 20 March · Final entry: 18 June · Exhibition: 12 November.']]},
  submissions:{title:'Submit <em>your work.</em>', kicker:'Open call · Volume 09', intro:'“After Image” is looking for new ways of seeing.', copy:'We welcome portfolios, single artworks, essays and critical writing from artists and writers worldwide. The next volume is interested in the residue of experience: memory, repair, blur, trace and atmosphere.', items:[['01','Visual portfolios / series','5–10 connected works, a 200–300 word concept statement and artist bio.'],['02','Single standout artwork','One exceptional work accompanied by medium, dimensions, year and a short note.'],['03','Essays & critical writing','800–1,500 words on process, contemporary art, law, preservation or wellbeing.']]},
  exhibitions:{title:'In the <em>room.</em>', kicker:'Exhibitions & partnerships', intro:'Work changes when it meets a body in space.', copy:'Our exhibitions bring award-winning and editorially featured artists into thoughtful dialogue with galleries, cultural institutions and collectors. Every show is built around attention rather than spectacle.', items:[['01','AURELIA Prize Exhibition','12–30 November 2026 · The Foundry, London · An exhibition of the 2026 award finalists.'],['02','Material Notes: Berlin','3–14 February 2027 · K47, Berlin · Works of material intensity across clay, pigment and metal.'],['03','Archive: Tokyo','8–19 April 2027 · Kiyosumi Atelier, Tokyo · An editorial exhibition for Volume 08.']]},
  about:{title:'An independent <em>voice.</em>', kicker:'About AURELIA', intro:'We believe attention is a form of care.', copy:'AURELIA was founded to place artists and their practices before market noise. We support human-made work, fair representation, and the interior life that makes a practice possible. Our editorial and advisory boards include curators, artists, writers and technical specialists across disciplines.', items:[['01','Editorial independence','We publish without commercial influence, and lead with perspective.'],['02','Artist rights','Artists retain full copyright. Features use limited, non-exclusive promotional rights.'],['03','Craft & authenticity','We focus on paintings, physical sculpture and material-led contemporary practice.'],['04','Our people','A cross-disciplinary board of painters, sculptors, historians and curators.']]},
  contact:{title:'Let’s start a <em>conversation.</em>', kicker:'Contact AURELIA', intro:'For collaborations, press, submissions and honest questions.', copy:'Select the most relevant contact route below. We endeavour to reply to editorial and partnership enquiries within five working days.', items:[]}
};
const d=data[page]; document.title=`AURELIA — ${d.kicker}`;
document.querySelector('#kicker').textContent=d.kicker; document.querySelector('#title').innerHTML=d.title; document.querySelector('#intro').textContent=d.intro; document.querySelector('#copy').textContent=d.copy;
const list=document.querySelector('#list');
if(page==='contact'){list.innerHTML=`<div class="contact-grid"><div class="contact-details"><div><h3>Editorial</h3><p>editorial@aurelia.art</p></div><div><h3>Awards administration</h3><p>awards@aurelia.art</p></div><div><h3>Press & partnerships</h3><p>hello@aurelia.art</p></div></div><form class="form-grid"><label>Subject<select><option>General inquiry</option><option>Award query</option><option>Magazine submission</option><option>Exhibition collaboration</option></select></label><label>Name<input placeholder="Your name"></label><label class="wide">Email<input type="email" placeholder="you@example.com"></label><label class="wide">Message<textarea placeholder="How can we help?"></textarea></label><button class="button button-dark wide" type="button">Send inquiry <span>↗</span></button></form></div>`}else{list.innerHTML=d.items.map(x=>`<article><b>${x[0]}</b><h2>${x[1]}</h2><p>${x[2]}</p><i>↗</i></article>`).join('')}
